# Generated by Django 3.1.6 on 2021-02-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_text_en', models.CharField(max_length=200, null=True)),
                ('question_text_fr', models.CharField(max_length=200, null=True)),
                ('question_text_ar', models.CharField(max_length=200, null=True)),
                ('question_text_tr', models.CharField(max_length=200, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('choice_text_en', models.CharField(max_length=200, null=True)),
                ('choice_text_fr', models.CharField(max_length=200, null=True)),
                ('choice_text_ar', models.CharField(max_length=200, null=True)),
                ('choice_text_tr', models.CharField(max_length=200, null=True)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traductionFEAE.question')),
            ],
        ),
    ]
